/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package birdgame;

public class App {
    public String getGreeting() {
        return "Game starting...";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new Game();
        
    }
}
